# frank_lloyd/apply_summary.py
#
# Plain-English apply summary generator for Frank Lloyd draft review.
#
# Before the operator clicks "Apply to Repo", they see a structured
# plain-English summary: what was built, which files, risk level,
# what validation passed, what happens on apply, and what's uncertain.
#
# The summary is generated by the cheap LM tier and cached at:
#   staging/frank_lloyd/{build_id}/stage2/apply_summary.json
#
# Re-generated on force=True or if the cache is absent.
# Deterministic fallback: if LM is unavailable, builds a minimal summary
# from the manifest and spec data without natural-language prose.
#
# Public API:
#   generate_apply_summary(build_id, force=False) → dict
#   Return shape: {ok, build_id, summary: {...}, cached, error}
#
# Summary shape:
#   {what_built, problem, files, risk, validation, on_apply, uncertainty, target_path}

from __future__ import annotations

import json
import pathlib
import re
from datetime import datetime, timezone
from typing import Optional

_ROOT      = pathlib.Path(__file__).resolve().parent.parent
_STAGING   = _ROOT / "staging" / "frank_lloyd"
_ARCHIVES  = _ROOT / "data" / "frank_lloyd" / "archives"

_SYSTEM_PROMPT = """\
You are summarizing a software draft for a non-technical operator who must \
decide whether to apply it to a live repository. Be honest and brief. \
Never exaggerate confidence. If something could fail, say so plainly.

Respond ONLY with a JSON object matching this exact schema:
{
  "what_built": "one sentence: what this module does",
  "problem":    "one sentence: what problem it solves",
  "files":      ["list of files that will be added or changed"],
  "risk":       "one sentence: risk level and why",
  "validation": "one sentence: what was checked and passed",
  "on_apply":   "one sentence: exactly what happens when the operator clicks Apply",
  "uncertainty":"one sentence: what is not certain / what to watch after apply",
  "target_path": "the target path in repo where the file will land (from manifest or spec)"
}
All values must be plain English strings (or a list of strings for 'files').
Do not add extra fields."""


# ── Public API ────────────────────────────────────────────────────────────────

def generate_apply_summary(build_id: str, force: bool = False) -> dict:
    """
    Return a plain-English apply summary for a draft_generated build.

    Reads artifacts from staging and archive. Uses LMHelper (cheap tier).
    Caches result at staging/frank_lloyd/{build_id}/stage2/apply_summary.json.
    Regenerates when force=True or cache is absent.

    Returns {ok, build_id, summary, cached, error}.
    """
    build_id = build_id.strip().upper()
    stage2_dir   = _STAGING / build_id / "stage2"
    cache_path   = stage2_dir / "apply_summary.json"
    archive_dir  = _ARCHIVES / build_id

    # Return cached result if available and not forced
    if cache_path.exists() and not force:
        try:
            cached = json.loads(cache_path.read_text(encoding="utf-8"))
            if "summary" in cached:
                return {
                    "ok":      True,
                    "build_id": build_id,
                    "summary": cached["summary"],
                    "cached":  True,
                    "error":   None,
                }
        except (OSError, json.JSONDecodeError):
            pass  # fall through to regenerate

    # ── Load artifacts ────────────────────────────────────────────────────────

    spec_yaml     = _read_text(archive_dir / "spec.yaml") or \
                    _read_text(_STAGING / build_id / "spec.yaml")
    request_json  = _read_json(archive_dir / "request.json")
    manifest      = _read_json(stage2_dir / "draft_manifest.json")
    draft_code    = _read_text(stage2_dir / "draft_module.py")
    draft_notes   = _read_text(stage2_dir / "draft_notes.md")

    if not manifest:
        return {
            "ok":      False,
            "build_id": build_id,
            "summary": None,
            "cached":  False,
            "error":   f"draft_manifest.json not found in staging for {build_id}. "
                       "Has a draft been generated yet?",
        }

    # ── Deterministic target path (strong source of truth for safe builds) ──────
    #
    # Read the planned new-file path from spec.yaml before calling the LM.
    # For CODE_DRAFT_LOW builds this is always reliable — it's set by the
    # validated spec, not guessed. The LM is never trusted over this value.

    det_target_path = (
        _extract_new_file_path(spec_yaml) or _extract_modified_file_path(spec_yaml)
    ) if spec_yaml else None

    # ── Build prompt context ──────────────────────────────────────────────────

    context_parts: list[str] = [f"Build ID: {build_id}"]

    if request_json:
        desc  = (request_json.get("description") or "").strip()
        title = (request_json.get("title") or "").strip()
        if title:
            context_parts.append(f"Title: {title}")
        if desc:
            context_parts.append(f"Request: {desc}")

    if spec_yaml:
        spec_excerpt = _extract_spec_classification(spec_yaml)
        if spec_excerpt:
            context_parts.append(f"Spec classification:\n{spec_excerpt}")

    files_generated = manifest.get("files_generated", [])
    model_used      = manifest.get("model_used", "unknown")
    task_class      = manifest.get("task_class", "unknown")

    context_parts.append(f"Task class: {task_class}")
    context_parts.append(f"Model used: {model_used}")
    context_parts.append(f"Files staged: {', '.join(files_generated)}")

    # Tell the LM the deterministic target path when known
    if det_target_path:
        context_parts.append(f"Planned target path (from spec): {det_target_path}")

    if draft_notes.strip():
        context_parts.append(f"Draft notes (excerpt):\n{draft_notes.strip()[:500]}")

    if draft_code.strip():
        context_parts.append(f"Draft code (excerpt):\n{draft_code.strip()[:800]}")

    user_content = "\n\n".join(context_parts)

    # ── LM call ───────────────────────────────────────────────────────────────

    from app.cost_warden import LMHelper
    helper = LMHelper("frank_lloyd", "apply_summary", max_tokens=400)
    lm_result = helper.call(system=_SYSTEM_PROMPT, user=user_content)

    if lm_result.ok:
        summary = _parse_summary(lm_result.content, manifest, spec_yaml)
    else:
        summary = _deterministic_summary(build_id, manifest, spec_yaml, request_json)

    # ── Override target_path with deterministic value (always wins for safe builds)
    if det_target_path:
        summary["target_path"] = det_target_path

    # ── Cache result ──────────────────────────────────────────────────────────

    try:
        stage2_dir.mkdir(parents=True, exist_ok=True)
        cache_payload = {
            "build_id":    build_id,
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "lm_ok":       lm_result.ok,
            "summary":     summary,
        }
        cache_path.write_text(json.dumps(cache_payload, indent=2), encoding="utf-8")
    except OSError:
        pass  # cache failure is non-fatal

    return {
        "ok":      True,
        "build_id": build_id,
        "summary": summary,
        "cached":  False,
        "error":   None,
    }


# ── Parsing helpers ───────────────────────────────────────────────────────────

def _parse_summary(content: str, manifest: dict, spec_yaml: str) -> dict:
    """
    Parse LM JSON response into summary dict.
    Falls back to deterministic summary on any parse failure.
    """
    _EXPECTED_KEYS = {
        "what_built", "problem", "files", "risk",
        "validation", "on_apply", "uncertainty", "target_path",
    }
    try:
        # Strip markdown fences if present
        text = content.strip()
        if text.startswith("```"):
            text = "\n".join(text.split("\n")[1:])
            if text.endswith("```"):
                text = text[:-3]
        parsed = json.loads(text.strip())
        # Validate required keys present
        if _EXPECTED_KEYS.issubset(parsed.keys()):
            return parsed
    except (json.JSONDecodeError, ValueError, AttributeError):
        pass
    return _deterministic_summary("", manifest, spec_yaml, None)


def _deterministic_summary(
    build_id: str,
    manifest: Optional[dict],
    spec_yaml: str,
    request_json: Optional[dict],
) -> dict:
    """Build a minimal summary from manifest/spec data without LM prose."""
    files     = (manifest or {}).get("files_generated", ["draft_module.py"])
    risk      = _extract_field_from_spec(spec_yaml, "risk_level") or "unknown"
    task_cls  = (manifest or {}).get("task_class", "unknown")
    desc      = ((request_json or {}).get("description") or "").strip()[:120]

    # Prefer spec's new-file list over manifest for multi-file builds
    spec_new_files = _extract_all_new_file_paths(spec_yaml) if spec_yaml else []
    all_files      = spec_new_files if spec_new_files else files
    det_path       = spec_new_files[0] if spec_new_files else ""

    return {
        "what_built":   desc or f"{build_id} module draft",
        "problem":      "See the spec for full details.",
        "files":        all_files,
        "risk":         f"Risk level: {risk}. Review spec for affected files.",
        "validation":   f"Spec validated ({task_cls}). Draft generated by Frank Lloyd.",
        "on_apply":     (
            f"{len(all_files)} file(s) will be written to the live repo."
            if len(all_files) > 1 else
            "draft_module.py will be copied to the target path in the live repo."
        ),
        "uncertainty":  "LM summary unavailable — review draft_module.py directly before applying.",
        "target_path":  det_path or "",
    }


def _extract_new_file_path(spec_yaml: str) -> Optional[str]:
    """
    Extract the first new-file path from spec.yaml affected_files.new section.
    Returns the path string, or None if the section is empty or absent.
    """
    paths = _extract_all_new_file_paths(spec_yaml)
    return paths[0] if paths else None


def _extract_all_new_file_paths(spec_yaml: str) -> list[str]:
    """
    Extract all new-file paths from spec.yaml affected_files.new section.

    Parses the format written by spec_writer._format_spec_yaml():
      affected_files:
        new:
          - path: "frank_lloyd/my_module.py"
            purpose: "..."
          - path: "tests/test_my_module.py"
            purpose: "..."

    Returns a list of path strings (empty list if section absent or empty).
    """
    lines = spec_yaml.splitlines()
    in_new = False
    paths: list[str] = []
    for line in lines:
        stripped = line.strip()
        if stripped == "new:":
            in_new = True
            continue
        if in_new:
            if stripped.startswith("modified:") or (stripped == "[]" and not paths):
                break
            m = re.match(r'\s*-\s*path:\s*"([^"]+)"', line)
            if m:
                path = m.group(1).strip()
                if path:
                    paths.append(path)
    return paths


def _extract_modified_file_path(spec_yaml: str) -> Optional[str]:
    """
    Extract the first modified-file path from spec.yaml affected_files.modified section.
    Returns the path string, or None if the section is empty or absent.
    """
    lines = spec_yaml.splitlines()
    in_modified = False
    for line in lines:
        stripped = line.strip()
        if stripped == "modified:":
            in_modified = True
            continue
        if in_modified:
            if stripped.startswith("new:") or stripped.startswith("affected_files:"):
                break
            m = re.match(r'\s*-\s*path:\s*"([^"]+)"', line)
            if m:
                path = m.group(1).strip()
                if path:
                    return path
    return None


def _extract_spec_classification(spec_yaml: str) -> str:
    """Extract just the classification block from spec.yaml for the LM prompt."""
    lines = spec_yaml.splitlines()
    result: list[str] = []
    in_block = False
    for line in lines:
        if "build classification" in line.lower() or "build_type" in line:
            in_block = True
        if in_block:
            result.append(line)
            # Stop after a blank line following the block
            if in_block and not line.strip() and result:
                break
    return "\n".join(result[:15])  # max 15 lines


def _extract_field_from_spec(spec_yaml: str, field: str) -> Optional[str]:
    """Extract a named field value from spec.yaml using simple regex."""
    import re
    match = re.search(
        rf"^\s*{re.escape(field)}\s*:\s*['\"]?(\w+)['\"]?",
        spec_yaml, re.MULTILINE,
    )
    return match.group(1) if match else None


# ── File helpers ──────────────────────────────────────────────────────────────

def _read_text(path: pathlib.Path) -> str:
    try:
        return path.read_text(encoding="utf-8") if path.exists() else ""
    except OSError:
        return ""


def _read_json(path: pathlib.Path) -> Optional[dict]:
    try:
        return json.loads(path.read_text(encoding="utf-8")) if path.exists() else None
    except (OSError, json.JSONDecodeError):
        return None
